---
- name: Ensure parameters
  sysctl:
    name: '{{ item.1.name }}'
    value: '{{ item.1.value }}'
    state: '{{ item.1.state | default("present") }}'
    sysctl_file: '{{ kernel_parameter_config_file_path }}/{{ item.0.filename | default(kernel_parameter_config_file_name) }}'
  ignore_errors: true
  with_subelements:
  - kernel_parameters
  - parameters
